### PR TITLE
feat: Move SPDX data to git submodule

### LINKED ISSUE #968: Pull in SPDX Licenses List
Modify the ORE-ERO to pull in the list of SPDX Licenses directly as opposed to needing to maintain a list ourselves.

https://github.com/spdx/license-list-data

### PR DESCRIPTION
**Pull request by nschonni**
Alternate take on #991
Closes #968

### CODE REVIEW

**Comment by simon332114** [comment]
There is also no option for the Non-SPDX-or-Public-Domain case, it was in the licences.yml file but the spdx list has no equivalent

**Comment by smellems** [comment]
I was doing some testing and added a check to exclude Deprecated liences.  Also only list OSI licences.

We could also do FSF, but I think it's more restrictive.  For example it doesn't include PHP licence

**Comment by smellems** [comment]
We could add an option in the preset for the Non-SPDX-or-Public-Domain

**Comment by simon332114** [comment]
Would it not work to have allow both FSF and OSI? It's not more restrictive if the licence only has to be accepted by either one instead of requiring both

**Comment by smellems** [comment]
True if it was OSI `or` FSF it would work and match GC Guidance.

I was testing with OSI `and` FSF

**Comment by nschonni** [comment]
@smellems the condition approach makes sense to me.
If you folks prefer to vendor in only the JSON file with maybe a script to keep it in sync, that's OK too.

**Pull request merged**
