### PR TITLE
Feat: dependencies page

### LINKED ISSUE #840: New area - "Dependencies"
Essentially, a new section to provide details on all the Dependencies the Crown Institutions have for their projects.

Ex: https://code.etalab.gouv.fr/en/deps/diverse-project

Ideally we'd have the ability to have dependencies listed as part of individual projects, and a section that provides the full list of Dependencies the various institutions are using so that we can provide the list for areas that we should spend time and resources in.

### PR DESCRIPTION
**Pull request by simon332114**
New version of dependencies page, loads significantly faster by removing duplicates of dependencies across administrations. Saves the dependencies in a single file rather than every administration having their own set of dependencies.
Should close #840

### CODE REVIEW

**Comment by ShadeWyrm** [comment]
@simon332114 - is this ready for review? Or still WIP?

**Comment by simon332114** [comment]
Ready for review, nothing to change unless improvements are required

**Comment by ShadeWyrm** [comment]
@simon332114 

Issues:
- Dependency Script is awesome! But a bit fragile, if it times out on any of the operations the whole thing dies, as well as a reproducible error under the ontario covid-19-self-assess tool.

'Remote end closed connection without response'
''cp932' codec can't encode character '\xc9' in position 14: illegal multibyte sequence'
 
This repo kills the script every time with the above ^
Checking : https://github.com/ongov/covid-19-self-assessment/archive/master.zip

On the UI side:
The filter for Organization does not work, and requires the Filter be cleared before any results will return again.

**Comment by simon332114** [comment]
I tried replicating the bug you mentioned but I can't seem to get it to drop the connection. The issue seems to be about the encoding and I'm almost certain cp932 isn't what I'm using.

**Pull request merged**
