### PR TITLE
Fix fields that take a null value in OSS yaml files

### PR DESCRIPTION
**Pull request by imadeDev**

### CODE REVIEW

**Comment by imadeDev** [comment]
In this commit I made the following changes:
- I replaced fields that contain null values with valid data
- I fixed some admincodes in the federal.yaml file
- change the started field with created field
- The projects where I dont find contact email I remove them
- the project where the created field is empty, I set the date of the metadataLastUpdated fields and I updated the metadataLastUpdated date to today's date

**Comment by smellems** [comment]
Related #170

**Comment by smellems** [comment]
Where we have a contact email and we're only missing name, description and started date, I would like to keep them and try to get the information.  I don't want to delete things that we know about and use (like RocketChat), just to add them back later.  Also if someone took the time to add data I'd like to keep it and try to get it updated.

Most of the APM data will be removed and that's good!

**Comment by smellems** [comment]
Also fixes #175

**Pull request merged**
