### PR TITLE
Custom form validation

### PR DESCRIPTION
**Pull request by WJXHenry**
For issue #140 

Implemented custom form validation. I am still unsure what the best restrictions are on the input fields, but I tried to create validations for them to my own discretion.

### CODE REVIEW

**Comment by WJXHenry** [comment]
I am unsure how to fix this error with lint:

image

**Comment by WJXHenry** [comment]
I modified the [ESLint configurations](https://eslint.org/docs/user-guide/configuring#specifying-environments) to allow for JQuery global variables.

**Comment by smellems** [comment]
Can we fix the issue just by changing the WET validation used?

See examples: https://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html

For First name they use `required="required" pattern=".{2,}" data-rule-minlength="2"` instead of lettersonly.

**Comment by WJXHenry** [comment]
Hey @smellems, the problem I found with using the existing WET validations is that they are either too restrictive (in the case of their letters only rule) or not strict enough. The `minlength` data rule is used for the first and last name validation examples but does not have any restrictions on the types of characters used - it will still be valid if characters like `?`, '@', '#', etc.. are inputted.

WET uses the [JQuery Validation Plugin](https://jqueryvalidation.org/documentation/) which is what I used for the custom validations. Having these custom validations allow us to have much more flexible form validation. Depending on how restrictive you want these form validations to be, I can try to implement them using the existing validations provided by WET.

__*Note*__
Here is the error message that will be thrown is we use the approach for first/last names provided in WET:

image

However, this data rule does not catch irregular characters:

image

The check passes with this input.

**Comment by imadeDev** [comment]
Hi @WJXHenry, You can use Wet Specialized validation: https://wet-boew.github.io/v4.0-ci/docs/ref/formvalid/formvalid-en.html
For example,  Name Field  You can  add  the Validation type : Letters only (data-rule-lettersonly="true")
<div class="form-group">
      <label for="nameContact">{{ site.NameContactCode[page.lang] }}</label>
      <input class="form-control" id="nameContact" name="nameContact" type="text" pattern="[A-Za-z\s]" data-rule-lettersonly="true" />
    </div>

**Comment by WJXHenry** [comment]
Hey @imadeDev, I found that if we use the `lettersonly` data rule, spaces or accents will not be allowed in the names. I believe that the current WET specialized validations are too restrictive for our purposes. Here are some inputs that I think should be valid but are flagged as invalid by the `lettersonly` data rule:

The space between the first and last name causes the error here:

image

The accent causes the error here:

image

I wasn't able to find a data rule in the WET specialized validations that could accurately validate the form input. Another thing I noticed is that the `pattern` attribute in the input does not seem to properly register or is being overwritten by the data rule.

**Pull request merged**
