### PR TITLE
Features/add yaml validation osc

### PR DESCRIPTION
**Pull request by imadeDev**
Create a schema and enable build validation of YAML files of the Open Source Code section

### CODE REVIEW

**Comment by smellems** [comment]
This looks good!

Please add non-mandatory fields?   Does the schema file have to be in the root?  Can we put it in the folder `_data/code` with the data?  Then we can have more than one schema.yaml file

**Comment by smellems** [comment]
For the errors, it's all having a URL instead of an Email contact.  Maybe this could be acceptable if we are adding projects without the contact being aware..

**Comment by imadeDev** [comment]
Does the schema file have to be in the root? Can we put it in the folder _data/code with the data?
Each YAML file it finds it will look in the same directory as that file for its schema, if there is no schema Yamale will keep looking up the directory tree until it finds one. If Yamale can not find a schema it will tell you.

**Comment by imadeDev** [comment]
Then we can have more than one schema.yaml file?
Yes we can have more than one schema.yaml file

**Comment by smellems** [comment]
#113

**Pull request merged**
