### PR TITLE
Removed required on new admin province when not municipal

### PR DESCRIPTION
**Pull request by fredericlestage-vdm**
Province is only required when orgLevel is municipal

### CODE REVIEW

**Comment by fredericlestage-vdm** [comment]
@smellems The no province for aboriginal and others rule came up when we discussed the new administration functionality and it was decided that it would only be mandatory for municipal administrations. Aboriginal and others can still add it, but it's not mandatory for them.

As for the provincial and federal administrations, it's unlikely that a new province will be created and the federal administration list is already complete. In the event of the creation of a new one, as they will be rare, we felt we could add them ourselves if need be.

**Comment by smellems** [comment]
But why?  Would aboriginal administration be in more than one province?  Would they rather not say where they are?

**Comment by fredericlestage-vdm** [comment]
Do aboriginal and others administration follow provincial laws? It made sense for municipalities since some laws change between provinces, but does that applies also to aboriginal or do they only follow federal laws?

I guess then "others" administration would likely be influenced by province, but in the case of companies, they might be international and not bound to any province or even country?

**Comment by fredericlestage-vdm** [comment]
@smellems As a side note, we did remove others from the new administration form and kept it only for the partners field in an earlier PR.

**Pull request merged**
