### PR TITLE
Feature/partners

### PR DESCRIPTION
**Pull request by fredericlestage-vdm**
Improved the partner field:
 - A partner must be an administration
 - You can add as many partners as you want
 - You can either select an existing partner and optionally add a contact (name & email) OR you can directly create a new administration, and optionally add a contact.
 - Improved the partner province select, it is now required only when creating a municipal administrations
 - Removed "others" administration from new admin form (but kept it in the new admin in partners preset)

### CODE REVIEW

**Comment by fredericlestage-vdm** [comment]
@smellems it was decided in a previous meeting that the schema pages would be moved to github only, so I decided not to waste time on it for this new element.

**Comment by smellems** [comment]
I think the schema pages were up to date until now.  This is maybe one of the final changes to the actual schema, it would be good to keep it up to date until it's moved.

If we move it.  I think we should keep it and add a link from the documentation.

**Comment by fredericlestage-vdm** [comment]
My understanding was that we would completely remove what we have now and make one more appropriate to GitHub, using .md files

**Comment by smellems** [comment]
Thanks for adding to the schema!

I noticed that if I select the ORE on the Code form the partners doesn't load correctly.  Administration should be selected and Name should be blank

image

**Comment by fredericlestage-vdm** [comment]
It's because the data it's fetching is the current data, and not the one I updated in the branch.

It's fetching from https://canada-ca.github.io/ore-ero/code.json and that file is not updated yet since I only changed it in this branch/PR

**Pull request merged**
